<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <InternalsVisibleTo>DunePresentation.Tests</InternalsVisibleTo>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DuneSession\DuneSession.csproj" />
    </ItemGroup>

</Project>
